spring:
  datasource:
    url: jdbc:mariadb://121.134.218.34:13306/kicktheworld
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'kicktheworld'
    password: 'kicktheworld1!'
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        show_sql: true
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
#
## 카카오 로그인 설정
#kakao :
#  client :
#    id : f6251fcbec1a0b926c225477ed4456a0
#    secret : DEybJxOQYf8i7JtYesj8byaSuWfz8dev
#  redirect :
#    url : http://localhost:9090/oauth2/code/kakao

server:
  port: 9090
