spring:
  datasource:
    url: jdbc:mariadb://211.62.99.58:8306/kicktheworld
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'kicktheworld'
    password: 'dmldusdmswjd1!'
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

jasypt:
  encryptor:
    password: JASYPTPASSWORD

chatgpt:
  api-key: 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



